### ISSUE TITLE
Problem about training setting

### ISSUE THREAD

**Issue by ygjwd12345** [lyndonzheng/F-LSeSim#1]
I plan to reproduce your work. May I ask if  `--learned_attn --augment` are used in the final result reported in the paper, such as Horse → Zebra FID 38.0 or not.
In the latest version, they are commented.

**Comment by lyndonzheng** [comment]
Hi @ygjwd12345, thanks for your comments. The score may be not exactly matched as 38.0 in the final epoch due to (1) the FID score is **sensitive to the small number of images**, which may be changed for different initial weights (following the existing CycleGAN and CUT, we have not fixed the initial weights); (2) As claimed in our paper and StyleGAN v2, the FID score tends to base **the decision much more on texture**, while humans focus on shape. Therefore, the best FID score does not report the best performance as human evaluation. 

Our reproduced results mean the results and performances are around or better than the reported performances. For example, we trained the fixed and learned version using this code and the corresponding FID scores are reported as below. You will find these scores are not exactly the same in every reproduction. 

Besides, the learned version needs local patches for contrastive learning. You also need to modify the --patch_size to 32, yet this training will be very slow due to the resampling for multiple local feature patches. Hence, our default setting is the fixed version with patch_size=64, which results in a low training cost, and yet competitive performance. 

![fid](https://user-images.githubusercontent.com/8929977/120730755-c0d2f280-c514-11eb-835e-68ca55a80ce0.jpg)
![fid](https://user-images.githubusercontent.com/8929977/120731179-a0576800-c515-11eb-8032-5f679762b486.jpg)
![fid](https://user-images.githubusercontent.com/8929977/120731332-f9270080-c515-11eb-9378-4a1921f20367.png)

**Comment by ygjwd12345** [comment]
Thanks for your reply. So using `--learned_attn --augment` means LSeSim and without `--learned_attn --augment` means FSeSim. Is ti correct?

**Comment by ygjwd12345** [comment]
![fid](https://user-images.githubusercontent.com/32895754/120789609-1cf83f80-c532-11eb-9d3d-f2b235827f33.jpg)
FSeSim result is quiet good.

**Comment by lyndonzheng** [comment]
@ygjwd12345 Sure, using `--leaned_attn --augment` means LSeSim, and it is better to use `--patch_size 32` for the learned version.  The FSeSim is faster, and then I set it as the default setting.

**Comment by ygjwd12345** [comment]
![fid](https://user-images.githubusercontent.com/32895754/121486238-405b3880-c9d1-11eb-9254-f28dadb80c03.jpg)
I also reproduce LSeSim the best result is 38.88, but much slower than FSeSim. I can live on this.
Thanks again.

**Comment by hughwcq** [comment]
Hi,may I ask you how to draw this graph and get fid during training?
