### ISSUE TITLE
About training on the winter2summer dataset

### ISSUE THREAD

**Issue by ZhenyuLiu-BJFU** [lyndonzheng/F-LSeSim#12]
Hello!
Thank you for doing such a good job.
And I am trying to train it on the winter2summer dataset, the settings are as yours.
I use the command --dataroot ./datasets/winter2summer --name winter2summer_SCL --model sc --learned_attn --augment to train the LSeSim model. I trained it about 50epoch and like this
![image](https://user-images.githubusercontent.com/74093654/164398321-82a22d34-6891-4456-863c-94e24541da84.png)
the FID=104.3
But  the effect is not as good as shown in your paper
![image](https://user-images.githubusercontent.com/74093654/164398223-edc17d61-1145-42ed-b1f8-50b43485550c.png)
Could you tell me what's wrong with me?

Thank you！

**Comment by lyndonzheng** [comment]
Hi @ZhenyuLiu-BJFU, thanks for your interesting. I have not trained the winter2summer on this code. I used the MUNIT(https://github.com/NVlabs/MUNIT) for winter2summer translation. 
For the results, it seems the structure is ensured well, while the appearance holds many artifacts that are not judged well by the discriminator. It may be better to add more weight for the discriminator loss, because the MUNIT used multi-scales discriminators with more weights on the GAN loss.

**Comment by ZhenyuLiu-BJFU** [comment]
Got it!
I try to train more time(about 90 epoch) and the result is
![image](https://user-images.githubusercontent.com/74093654/164585328-b728bf04-7551-4c2a-afe8-b1ecf6d5b761.png)
Most of the pictures have blue parts, I think it's a little strange. 
Of course, I used FID to test the effect and found that FID=87.8, it seems not bad.
What do you think of this effect?

Thank you!

**Comment by lyndonzheng** [comment]
Hi @ZhenyuLiu-BJFU I have not noticed you training epoch before. Generally, the default setting would be 200 times for fixed unpaired I2I translation, while the learnable one following the setting of CUT that use 400 epochs during the training.

**Comment by ZhenyuLiu-BJFU** [comment]
Thanks for your explanation.
I will try it again.
