### ISSUE TITLE
Why normalize the feature by "/ np.sqrt(C)"

### ISSUE THREAD

**Issue by o0t1ng0o** [lyndonzheng/F-LSeSim#7]
Hi, @lyndonzheng 

I have a question about the normalization of the extracted feature.
As shown in line 221, the code normalizes the feature by dividing the feature by "np.sqrt(C)".
Is there any meaning about np.sqrt(C)?
https://github.com/lyndonzheng/F-LSeSim/blob/e092e62ed8a2f51f3661630e1522ec2549ec31d3/models/losses.py#L221

Thank you in advance.

**Comment by o0t1ng0o** [comment]
In addition, I found that you divide the similarity map by 10 when calculating the similarity map.
Is there any reason for this?

https://github.com/lyndonzheng/F-LSeSim/blob/e092e62ed8a2f51f3661630e1522ec2549ec31d3/models/losses.py#L223

**Comment by lyndonzheng** [comment]
> Hi, @lyndonzheng
> 
> I have a question about the normalization of the extracted feature.
> As shown in line 221, the code normalizes the feature by dividing the feature by "np.sqrt(C)".
> Is there any meaning about np.sqrt(C)?
> https://github.com/lyndonzheng/F-LSeSim/blob/e092e62ed8a2f51f3661630e1522ec2549ec31d3/models/losses.py#L221
> 
> Thank you in advance.

Hi @o0t1ng0o, there are many operations to calculate the spatially-correlative relationships. If we use the _norm_, the distance is the **cosine** distance. Otherwise, it will be computed as Dot product as the operation used in **self-attention**. Please refer to [Non-Local](https://openaccess.thecvf.com/content_cvpr_2018/papers/Wang_Non-Local_Neural_Networks_CVPR_2018_paper.pdf) for more details. 

Dividing by 10 is for long-range gradient.

**Comment by o0t1ng0o** [comment]
Thank you very much.
